### ISSUE TITLE
issue in uploading GPR data

### ISSUE THREAD

**Issue by arnab-pal** [xiongGPR/GPRlab#1]
I have tried to upload my GPR data in .dzt format. But upon multiple trial it is not uploading and showing "loading data" for a long time. Please resolve the problem.

**Comment by erbiaoger** [comment]
Can you give me some more details, like screenshots etc?

**Comment by arnab-pal** [comment]
![Screenshot 2024-06-25 174745](https://github.com/xiongGPR/GPRlab/assets/62827543/066da994-9533-463f-bf65-87379406c359)
![Screenshot 2024-06-25 174823](https://github.com/xiongGPR/GPRlab/assets/62827543/4010dc94-b018-414e-869c-e37234bd9712)

**Comment by erbiaoger** [comment]
Ok, we'll get back to you later.

**Comment by erbiaoger** [comment]
And, hope you can always pay attention to this issues.

**Comment by xiongGPR** [comment]
I need some of your data to test the specific cause of the error. Are you collecting single channel data?


K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiongGPR/GPRlab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 晚上8:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [xiongGPR/GPRlab] issue in uploading GPR data (Issue #1)





 
Screenshot.2024-06-25.174745.png (view on web)
 Screenshot.2024-06-25.174823.png (view on web)

**Comment by arnab-pal** [comment]
Yes, I am collecting single-channel data. But I can't share the data because of confidentiality issues. I understood that the size of the GPR data is very high which is creating the problem.

Thanking you

**Comment by xiongGPR** [comment]
Your error seems to be caused by the number of AD digits. I fixed a similar issue earlier. 
Therefore, (1) you can try downloading the "GPRlab. mlappinstall" installation software again (if you are not using this version). 
(2) You can try reducing the size of the data body, although I don't think that's the reason.
&nbsp;


K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月25日(星期二) 晚上9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiongGPR/GPRlab] issue in uploading GPR data (Issue #1)














 
Yes, I am collecting single-channel data. But I can't share the data because of confidentiality issues. I understood that the size of the GPR data is very high which is creating the problem.
 
Thanking you

**Comment by xiongGPR** [comment]
(3) You can try using "readdz_GPRlab. m" to read your raw data and then process it.


K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiongGPR/GPRlab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiongGPR/GPRlab] issue in uploading GPR data (Issue #1)





 
Yes, I am collecting single-channel data. But I can't share the data because of confidentiality issues. I understood that the size of the GPR data is very high which is creating the problem.
 
Thanking you

**Comment by arnab-pal** [comment]
Can you share the link of this software file. It will be helpful.

Thanking you

**Comment by xiongGPR** [comment]
In the root directory
![1719322284375](https://github.com/xiongGPR/GPRlab/assets/107855719/51b73e9c-3b2b-4cf4-bc1c-dc9211dd3916)

**Comment by erbiaoger** [comment]
OK, the issue has ended.
